try:
    print(x)
except:
    print("An error or something went wrong!")
finally:
    print("Exception handling is completed!")


try:
    print("Helloo there...")
except:
    print("An error or something went wrong!")
finally:
    print("Exception handling is completed!")
